FROM debian@sha256:f37a335e82bca302e955fa39f9dfe28f1be618f016f8a2b56318e5a5111afc26

COPY node_config_reader.sh /usr/local/bin/node-config-reader
RUN chmod 0755 /usr/local/bin/node-config-reader
ENTRYPOINT ["/usr/local/bin/node-config-reader"]
